# Generated by Django 5.2.13 on 2026-04-15 06:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('image_url', models.CharField(blank=True, max_length=255)),
                ('quantity_available', models.IntegerField(default=0)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('order_number', models.CharField(blank=True, max_length=100)),
                ('min_quantity', models.IntegerField(default=0)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('supplier', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('business_group', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'accessories',
                'ordering': ['item_name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('business_group', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('badge_number', models.CharField(blank=True, max_length=50)),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff')], default='STAFF', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.CharField(blank=True, max_length=255)),
                ('asset_tag', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('Laptop', 'Laptop'), ('Phone', 'Phone'), ('Tablet', 'Tablet'), ('PC', 'PC'), ('Monitor', 'Monitor'), ('Accessory', 'Accessory'), ('Other', 'Other')], default='Other', max_length=50)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('DEPLOYED', 'Deployed'), ('IN_REPAIR', 'In Repair'), ('IN_MAINTENANCE', 'In Maintenance'), ('LOST', 'Lost'), ('TO_AUDIT', 'To Audit')], default='AVAILABLE', max_length=50)),
                ('serial_number', models.CharField(blank=True, max_length=255)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('end_of_life', models.DateField(blank=True, null=True)),
                ('order_number', models.CharField(blank=True, max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('depreciation_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('supplier', models.CharField(blank=True, max_length=100)),
                ('business_group', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('group', models.CharField(blank=True, choices=[('PRODUCT', 'Product'), ('PARTS', 'Parts')], max_length=20)),
                ('imei_number', models.CharField(blank=True, max_length=20)),
                ('ssd_encryption_status', models.CharField(blank=True, choices=[('ENABLED', 'Enabled'), ('DISABLED', 'Disabled'), ('N/A', 'N/A')], max_length=20)),
                ('connectivity', models.CharField(blank=True, max_length=100)),
                ('cpu', models.CharField(blank=True, max_length=100)),
                ('gpu', models.CharField(blank=True, max_length=100)),
                ('operating_system', models.CharField(blank=True, max_length=100)),
                ('ram', models.CharField(blank=True, max_length=50)),
                ('screen_size', models.CharField(blank=True, max_length=10)),
                ('storage_size', models.CharField(blank=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['asset_tag'],
            },
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction_type', models.CharField(choices=[('CHECK_OUT', 'Check Out'), ('CHECK_IN', 'Check In'), ('TRANSFER', 'Transfer'), ('ADJUSTMENT', 'Adjustment')], max_length=30)),
                ('event_description', models.TextField(blank=True)),
                ('quantity', models.IntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accessory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_logs', to='api.accessory')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_logs', to='api.asset')),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_transactions', to=settings.AUTH_USER_MODEL)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performed_transactions', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
    ]
