# Generated by Django 5.2.13 on 2026-04-20 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_seed_demo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='business_group',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='connectivity',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='ssd_encryption_status',
        ),
        migrations.AddField(
            model_name='asset',
            name='model',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
