# Generated by Django 5.2.13 on 2026-04-20 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_asset_remove_image_dept_ssd_connectivity_add_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessory',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image_url',
        ),
    ]
