# Generated by Django 5.2.13 on 2026-04-20 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_image_url_from_user_and_accessory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessory',
            name='business_group',
        ),
    ]
