# Generated by Django 5.2.13 on 2026-04-20 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_business_group_from_accessory'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='archive_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='accessory',
            name='archive_reason',
            field=models.CharField(blank=True, choices=[('DELETED', 'Deleted'), ('RETIRED', 'Retired')], max_length=20),
        ),
        migrations.AddField(
            model_name='accessory',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessory',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accessory',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='archive_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='archive_reason',
            field=models.CharField(blank=True, choices=[('DELETED', 'Deleted'), ('RETIRED', 'Retired')], max_length=20),
        ),
        migrations.AddField(
            model_name='asset',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='archive_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='archive_reason',
            field=models.CharField(blank=True, choices=[('DELETED', 'Deleted'), ('RETIRED', 'Retired')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='transaction_type',
            field=models.CharField(choices=[('CHECK_OUT', 'Check Out'), ('CHECK_IN', 'Check In'), ('TRANSFER', 'Transfer'), ('ADJUSTMENT', 'Adjustment'), ('ARCHIVE', 'Archive'), ('RESTORE', 'Restore')], max_length=30),
        ),
    ]
