# Generated by Django 5.2.13 on 2026-04-22 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_archive_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='transaction_type',
            field=models.CharField(choices=[('CHECK_OUT', 'Check Out'), ('CHECK_IN', 'Check In'), ('TRANSFER', 'Transfer'), ('ADJUSTMENT', 'Adjustment'), ('ARCHIVE', 'Archive'), ('RESTORE', 'Restore'), ('STATUS_IN_REPAIR', 'Set to In Repair'), ('STATUS_IN_MAINTENANCE', 'Set to In Maintenance'), ('STATUS_LOST', 'Marked as Lost'), ('STATUS_TO_AUDIT', 'Flagged for Audit'), ('STATUS_AVAILABLE', 'Marked Available'), ('STATUS_DEPLOYED', 'Set to Deployed')], max_length=30),
        ),
    ]
