# Generated by Django 5.2.13 on 2026-04-22 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_transactionlog_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('AVAILABLE', 'Available'), ('DEPLOYED', 'Deployed'), ('IN_REPAIR', 'In Repair'), ('IN_MAINTENANCE', 'In Maintenance'), ('LOST', 'Lost'), ('TO_AUDIT', 'To Audit')], max_length=50, null=True),
        ),
    ]
