# Generated by Django 5.2.13 on 2026-04-28 07:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_asset_previous_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Phone', 'Phone'), ('Tablet', 'Tablet'), ('PC', 'PC'), ('Monitor', 'Monitor'), ('Accessory', 'Accessory'), ('Other', 'Other')], db_index=True, default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='group',
            field=models.CharField(blank=True, choices=[('PRODUCT', 'Product'), ('PARTS', 'Parts')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('DEPLOYED', 'Deployed'), ('IN_REPAIR', 'In Repair'), ('IN_MAINTENANCE', 'In Maintenance'), ('LOST', 'Lost'), ('TO_AUDIT', 'To Audit')], db_index=True, default='AVAILABLE', max_length=50),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='transaction_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='transaction_type',
            field=models.CharField(choices=[('CHECK_OUT', 'Check Out'), ('CHECK_IN', 'Check In'), ('TRANSFER', 'Transfer'), ('ADJUSTMENT', 'Adjustment'), ('ARCHIVE', 'Archive'), ('RESTORE', 'Restore'), ('STATUS_IN_REPAIR', 'Set to In Repair'), ('STATUS_IN_MAINTENANCE', 'Set to In Maintenance'), ('STATUS_LOST', 'Marked as Lost'), ('STATUS_TO_AUDIT', 'Flagged for Audit'), ('STATUS_AVAILABLE', 'Marked Available'), ('STATUS_DEPLOYED', 'Set to Deployed')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff')], db_index=True, default='STAFF', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='transactionlog',
            constraint=models.CheckConstraint(condition=models.Q(('asset__isnull', False), ('accessory__isnull', False), ('to_user__isnull', False), ('from_user__isnull', False), _connector='OR'), name='txlog_has_target'),
        ),
    ]
