services:
  - type: web
    name: pandora-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: gunicorn core.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://your-vercel-app.vercel.app"